### PR TITLE
predicate elimination

### PR DESCRIPTION
**Pull request by matej21**
This change is [Reviewable](https://reviewable.io/reviews/contember/engine/304)

### CODE REVIEW

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed 7 of 28 files at r1, 3 of 14 files at r2, 2 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/304)* status: 12 of 33 files reviewed, 4 unresolved discussions (waiting on @JanTvrdik and @matej21)

___
*[`packages/engine-content-api/src/acl/EvaluatedPredicateReplacer.ts` line 30 at r4](https://reviewable.io/reviews/contember/engine/304#-N8Ok871EFjai4UV7DMn:-N8Ok8726v-Su7Leaax4:b-jy50n0) ([raw file](https://github.com/contember/engine/blob/343bec5ad909fb1724c64f854c6b4ee6a4226abd/packages/engine-content-api/src/acl/EvaluatedPredicateReplacer.ts#L30)):*
> ```XML
> 					parts.push(this.replaceInternal(sub, onRelation))
> 				}
> 				result[key] = parts
> ```

`result[key] = value.map(it => this.replaceInternal(...))`
___
*[`packages/engine-content-api/src/acl/EvaluatedPredicateReplacer.ts` line 32 at r4](https://reviewable.io/reviews/contember/engine/304#-N8OkaZH8FjW-7BiICG9:-N8OkaZH8FjW-7BiICGA:b-69fcs9) ([raw file](https://github.com/contember/engine/blob/343bec5ad909fb1724c64f854c6b4ee6a4226abd/packages/engine-content-api/src/acl/EvaluatedPredicateReplacer.ts#L32)):*
> ```XML
> 				result[key] = parts
> 
> 			} else if (key === this.relation.name) {
> ```

maybe `key === this.relation.name && !onRelation`?
___
*[`packages/engine-content-api/src/acl/PredicatesInjector.ts` line 59 at r4](https://reviewable.io/reviews/contember/engine/304#-N8OqfZl29BbX7gWR2k7:-N8OqeRq7MO5YxgyJws3:b-j4m80q) ([raw file](https://github.com/contember/engine/blob/343bec5ad909fb1724c64f854c6b4ee6a4226abd/packages/engine-content-api/src/acl/PredicatesInjector.ts#L59)):*
> ```XML
> 			}
> 		}
> 		const fieldsForPredicate = fields.filter(it => !isRoot || this.predicateFactory.shouldApplyCellLevelPredicate(entity, Acl.Operation.read, it))
> ```

move constant condition out of filter loop

~~~tsx
const  fieldsForPredicate = isRoot
  ? fields.filter(it =>  this.predicateFactory.shouldApplyCellLevelPredicate(entity, Acl.Operation.read, it)))
  : fields
~~~
___
*[`packages/engine-content-api/src/mapper/select/optimizer/ConditionOptimizer.ts` line 30 at r4](https://reviewable.io/reviews/contember/engine/304#-N8Sf6tS1Ba_HeYKO8ZX:-N8Sf6tS1Ba_HeYKO8ZY:bb7r2f0) ([raw file](https://github.com/contember/engine/blob/343bec5ad909fb1724c64f854c6b4ee6a4226abd/packages/engine-content-api/src/mapper/select/optimizer/ConditionOptimizer.ts#L30)):*
> ```XML
> 
> 			} else if (key === 'or' || key === 'and') {
> 				const parts = (value as readonly Input.Condition[]).filter(it => !!it).map(it => this.optimizeCondition(it))
> ```

why?



_Code quote:_
```XML
filter(it => !!it)
```

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/304)* status: 12 of 33 files reviewed, 4 unresolved discussions (waiting on @JanTvrdik)

___
*[`packages/engine-content-api/src/acl/EvaluatedPredicateReplacer.ts` line 30 at r4](https://reviewable.io/reviews/contember/engine/304#-N8Ok871EFjai4UV7DMn:-N8Tp_8s9oqVfQtQ-HpB:b-896fix) ([raw file](https://github.com/contember/engine/blob/343bec5ad909fb1724c64f854c6b4ee6a4226abd/packages/engine-content-api/src/acl/EvaluatedPredicateReplacer.ts#L30)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

`result[key] = value.map(it => this.replaceInternal(...))`
</blockquote></details>

Done.
___
*[`packages/engine-content-api/src/acl/EvaluatedPredicateReplacer.ts` line 32 at r4](https://reviewable.io/reviews/contember/engine/304#-N8OkaZH8FjW-7BiICG9:-N8Tp_MNBszuVBcTsZSE:b-896fix) ([raw file](https://github.com/contember/engine/blob/343bec5ad909fb1724c64f854c6b4ee6a4226abd/packages/engine-content-api/src/acl/EvaluatedPredicateReplacer.ts#L32)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

maybe `key === this.relation.name && !onRelation`?
</blockquote></details>

Done.
___
*[`packages/engine-content-api/src/acl/PredicatesInjector.ts` line 59 at r4](https://reviewable.io/reviews/contember/engine/304#-N8OqfZl29BbX7gWR2k7:-N8TpoLEE1JWxOWorKj0:b-896fix) ([raw file](https://github.com/contember/engine/blob/343bec5ad909fb1724c64f854c6b4ee6a4226abd/packages/engine-content-api/src/acl/PredicatesInjector.ts#L59)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

move constant condition out of filter loop

~~~tsx
const  fieldsForPredicate = isRoot
  ? fields.filter(it =>  this.predicateFactory.shouldApplyCellLevelPredicate(entity, Acl.Operation.read, it)))
  : fields
~~~
</blockquote></details>

Done.
___
*[`packages/engine-content-api/src/mapper/select/optimizer/ConditionOptimizer.ts` line 30 at r4](https://reviewable.io/reviews/contember/engine/304#-N8Sf6tS1Ba_HeYKO8ZX:-N8TqJN5Dz-9WQTsCTD_:b-896fix) ([raw file](https://github.com/contember/engine/blob/343bec5ad909fb1724c64f854c6b4ee6a4226abd/packages/engine-content-api/src/mapper/select/optimizer/ConditionOptimizer.ts#L30)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

why?
</blockquote></details>

Done.

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed 10 of 28 files at r1, 8 of 14 files at r2, 1 of 5 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/304)* status: all files reviewed, 6 unresolved discussions (waiting on @matej21)

___
*[`packages/engine-content-api/src/mapper/select/optimizer/ConditionOptimizer.ts` line 25 at r6](https://reviewable.io/reviews/contember/engine/304#-N8TtreL2emlw33HIlWg:-N8TtreL2emlw33HIlWh:b-iosyb1) ([raw file](https://github.com/contember/engine/blob/842ac34a8b7d12e481faef8a652b941accfde39e/packages/engine-content-api/src/mapper/select/optimizer/ConditionOptimizer.ts#L25)):*
> ```XML
> 		for (const [key, value] of Object.entries(condition)) {
> 			if (value === undefined || value === null) {
> 				// do nothing
> ```

this is not covered by condition optimizer unit tests

~~~tsx
	it('remove conditions with null value', () => {
		assert.deepStrictEqual(optimizer.optimize({ eq: null }), {})
	})

	it('remove conditions with undefined value', () => {
		assert.deepStrictEqual(optimizer.optimize({ eq: undefined }), {})
	})
~~~
___
*[`packages/engine-content-api/src/mapper/select/optimizer/ConditionOptimizer.ts` line 29 at r6](https://reviewable.io/reviews/contember/engine/304#-N8Tsf4140lo0b7uBCUU:-N8Tsf4140lo0b7uBCUV:b-1cl2tc) ([raw file](https://github.com/contember/engine/blob/842ac34a8b7d12e481faef8a652b941accfde39e/packages/engine-content-api/src/mapper/select/optimizer/ConditionOptimizer.ts#L29)):*
> ```XML
> 				resultCollector.add(true, 'and')
> 
> 			} else if (key === 'or' || key === 'and') {
> ```

it think it would be more readable to split the branches and remove optimizeJunction.
___
*[`packages/engine-content-api/src/mapper/select/optimizer/helpers.ts` line 18 at r6](https://reviewable.io/reviews/contember/engine/304#-N8TvL4O1FN2-_GAzPmD:-N8TvL4O1FN2-_GAzPmE:b-e1oatk) ([raw file](https://github.com/contember/engine/blob/842ac34a8b7d12e481faef8a652b941accfde39e/packages/engine-content-api/src/mapper/select/optimizer/helpers.ts#L18)):*
> ```XML
> 			return true
> 		} else if (part !== false) {
> 			resultParts.push((part.length === 1 ? part[0] : { and: part }) as P)
> ```

I feel like I've see this ternary couple of times in this file
___
*[`packages/engine-content-api/src/mapper/select/optimizer/helpers.ts` line 59 at r6](https://reviewable.io/reviews/contember/engine/304#-N8TwVxN6RqPTll7f5D2:-N8TwVxN6RqPTll7f5D3:b-j01z1p) ([raw file](https://github.com/contember/engine/blob/842ac34a8b7d12e481faef8a652b941accfde39e/packages/engine-content-api/src/mapper/select/optimizer/helpers.ts#L59)):*
> ```XML
> 
> 	public add(value: T[] | boolean, wrapper: 'not' | 'or' | 'and'): void {
> 		if (wrapper === 'not' && typeof value === 'boolean') {
> ```

should be move to `optimizeNot` for symmetry with `and` / `or`
___
*[`packages/engine-content-api/src/mapper/select/optimizer/helpers.ts` line 80 at r6](https://reviewable.io/reviews/contember/engine/304#-N8TxYUdC8fQn6-cHeh8:-N8TxYUdC8fQn6-cHeh9:bkyg17q) ([raw file](https://github.com/contember/engine/blob/842ac34a8b7d12e481faef8a652b941accfde39e/packages/engine-content-api/src/mapper/select/optimizer/helpers.ts#L80)):*
> ```XML
> 	}
> 
> 	public getResult(): T[] | boolean {
> ```

should ideally reuse optimizeAnd logic
___
*[`packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts` line 26 at r6](https://reviewable.io/reviews/contember/engine/304#-N8Txz5z7IQ1YXfrm8ir:-N8Txz5z7IQ1YXfrm8is:b-hehts0) ([raw file](https://github.com/contember/engine/blob/842ac34a8b7d12e481faef8a652b941accfde39e/packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts#L26)):*
> ```XML
> 		}
> 
> 		return result.length === 1 ? result[0] : { and: result }
> ```

you're combining three multi if strategies (1) elseif 2) standalone ifs 3) ternary) in single function



_Suggestion:_
```XML
		if (result === false) {
			return { [entity.primary]: { never: true } }
		} else if (result === true) {
			return { [entity.primary]: { always: true } }
		} else if (result.length === 0) {
			return {}
		} else if (result.length === 1) {
			return result[0]
		} else {
			return { and: result }
		}
```

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/304)* status: 29 of 33 files reviewed, 6 unresolved discussions (waiting on @JanTvrdik and @matej21)

___
*[`packages/engine-content-api/src/mapper/select/optimizer/helpers.ts` line 37 at r7](https://reviewable.io/reviews/contember/engine/304#-N8U6q6RARkYQvV_FooB:-N8U6q6RARkYQvV_FooC:b-7ej2m5) ([raw file](https://github.com/contember/engine/blob/dd1ecfd1c00ff66882c9befd5059d417404f7ff5/packages/engine-content-api/src/mapper/select/optimizer/helpers.ts#L37)):*
> ```XML
> 		} else if (part === false) {
> 			return false
> 		} else {
> ```

save one branch with this easy trick



_Suggestion:_
```XML
} else if (part !== undefined) {
```

**Review by JanTvrdik — COMMENTED** [review]
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/304)* status: all files reviewed, 3 unresolved discussions (waiting on @matej21)

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/304)* status: all files reviewed, 3 unresolved discussions (waiting on @JanTvrdik)

___
*[`packages/engine-content-api/src/mapper/select/optimizer/ConditionOptimizer.ts` line 25 at r6](https://reviewable.io/reviews/contember/engine/304#-N8TtreL2emlw33HIlWg:-N8UA9L3DPN0dibBbPkI:b-896fix) ([raw file](https://github.com/contember/engine/blob/842ac34a8b7d12e481faef8a652b941accfde39e/packages/engine-content-api/src/mapper/select/optimizer/ConditionOptimizer.ts#L25)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

this is not covered by condition optimizer unit tests

~~~tsx
	it('remove conditions with null value', () => {
		assert.deepStrictEqual(optimizer.optimize({ eq: null }), {})
	})

	it('remove conditions with undefined value', () => {
		assert.deepStrictEqual(optimizer.optimize({ eq: undefined }), {})
	})
~~~
</blockquote></details>

Done.
___
*[`packages/engine-content-api/src/mapper/select/optimizer/ConditionOptimizer.ts` line 29 at r6](https://reviewable.io/reviews/contember/engine/304#-N8Tsf4140lo0b7uBCUU:-N8UABgsA4F9qeX-1HCm:b-896fix) ([raw file](https://github.com/contember/engine/blob/842ac34a8b7d12e481faef8a652b941accfde39e/packages/engine-content-api/src/mapper/select/optimizer/ConditionOptimizer.ts#L29)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

it think it would be more readable to split the branches and remove optimizeJunction.
</blockquote></details>

Done.
___
*[`packages/engine-content-api/src/mapper/select/optimizer/helpers.ts` line 37 at r7](https://reviewable.io/reviews/contember/engine/304#-N8U6q6RARkYQvV_FooB:-N8U9Exc1oEwyHk53-Av:b-896fix) ([raw file](https://github.com/contember/engine/blob/dd1ecfd1c00ff66882c9befd5059d417404f7ff5/packages/engine-content-api/src/mapper/select/optimizer/helpers.ts#L37)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

save one branch with this easy trick
</blockquote></details>

Done.

**Review by JanTvrdik — COMMENTED** [review]
> Reviewed 2 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/304)* status: 31 of 33 files reviewed, all discussions resolved (waiting on @JanTvrdik)

**Review by JanTvrdik — APPROVED** [review]
> Reviewed 2 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/304)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)

**Review by JanTvrdik — APPROVED** [review]
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/304)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)

**Pull request merged**
