### PR TITLE
Import & export

### PR DESCRIPTION
**Pull request by JanTvrdik**
This change is [Reviewable](https://reviewable.io/reviews/contember/engine/285)

### CODE REVIEW

**Review by matej21 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/285)* status: all files reviewed, 17 unresolved discussions (waiting on @JanTvrdik)

___
*[`packages/engine-http/src/transfer/ContentExporter.ts` line 3 at r1](https://reviewable.io/reviews/contember/engine/285#-N3sw4Dj3_3Jfbtnua9n:-N3sw4Dj3_3Jfbtnua9o:bzbxu7b) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentExporter.ts#L3)):*
> ```XML
> import { Client, Compiler, Connection } from '@contember/database'
> import { Schema } from '@contember/schema'
> import { Command } from './Command.js'
> ```

we don't use `.js` imports in engine (yet)
___
*[`packages/engine-http/src/transfer/ContentExporter.ts` line 5 at r1](https://reviewable.io/reviews/contember/engine/285#-N3sygfFCcXRKRxUS7vm:-N3sygfFCcXRKRxUS7vn:b-65sh45) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentExporter.ts#L5)):*
> ```XML
> import { Command } from './Command.js'
> import { PgSchema, PgSchemaBuilder, PgTableSchema } from './PgSchemaBuilder.js'
> import TransactionLike = Connection.TransactionLike
> ```

please do not use this import type aliases
___
*[`packages/engine-http/src/transfer/ContentExporter.ts` line 7 at r1](https://reviewable.io/reviews/contember/engine/285#-N3t0RNMDIep9hFW3oEC:-N3t0RNMDIep9hFW3oED:bb7pa6j) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentExporter.ts#L7)):*
> ```XML
> import TransactionLike = Connection.TransactionLike
> 
> // TODO: checkMigrationHash
> ```

todo
___
*[`packages/engine-http/src/transfer/ContentExporter.ts` line 19 at r1](https://reviewable.io/reviews/contember/engine/285#-N3syqtU1AUzb1PbvQGM:-N3syqtU1AUzb1PbvQGN:b-tplpmn) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentExporter.ts#L19)):*
> ```XML
> 	}
> 
> 	private async* asyncIterableTransaction<T>(db: Client, cb: (db2: Client<TransactionLike>) => AsyncIterable<T>): AsyncIterable<T> {
> ```

move this to database as a utility function
___
*[`packages/engine-http/src/transfer/ContentExporter.ts` line 40 at r1](https://reviewable.io/reviews/contember/engine/285#-N3sz0cZDmqH9iJUc80F:-N3sz0cZDmqH9iJUc80G:btnz84g) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentExporter.ts#L40)):*
> ```XML
> 		for await (const command of commands) {
> 			yield Buffer.from(JSON.stringify(command))
> 			yield Buffer.from('\n')
> ```

isn't it possible to create this new-line buffer just once?
___
*[`packages/engine-http/src/transfer/ContentExporter.ts` line 57 at r1](https://reviewable.io/reviews/contember/engine/285#-N3t6_FEA9V7Qt9m5tRW:-N3t6_FEA9V7Qt9m5tRX:b-xb5tju) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentExporter.ts#L57)):*
> ```XML
> 		let empty = true
> 
> 		for await (const row of this.cursorQuery(db, 100, query.sql, query.parameters)) {
> ```

isn't 100 too low? have you tried some benchmarks?
___
*[`packages/engine-http/src/transfer/ContentImporter.ts` line 46 at r1](https://reviewable.io/reviews/contember/engine/285#-N3tAta95Npado2GA9KM:-N3tAta95Npado2GA9KN:by3ghsk) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentImporter.ts#L46)):*
> ```XML
> 			} else if (commandName === 'insertBegin') {
> 				if (insertContext !== null) {
> 					throw new Error(`You need to call insertEnd before calling ${commandName}`)
> ```

this will cause internal server error 500, right? it needs to be handled.
___
*[`packages/engine-http/src/transfer/ContentImporter.ts` line 93 at r1](https://reviewable.io/reviews/contember/engine/285#-N3tBpGu1UvjX1ojvgHg:-N3tBpGu1UvjX1ojvgHh:bgs6z7n) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentImporter.ts#L93)):*
> ```XML
> 		const row = '(' + repeatAndJoin('?', ', ', context.columns.length) + ')'
> 		const rows = repeatAndJoin(row, ',\n', context.rows.length)
> 		const sql = `INSERT INTO ${tableQuoted} ${columnsQuoted} VALUES\n${rows}`
> ```

maybe add `batch` method to InsertBuilder in database?
___
*[`packages/engine-http/src/transfer/ContentImporter.ts` line 103 at r1](https://reviewable.io/reviews/contember/engine/285#-N3tBVnY8L4XS6MADvz7:-N3tBVnY8L4XS6MADvz8:b-91o8dv) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentImporter.ts#L103)):*
> ```XML
> 
> 		await db.query(sql, parameters)
> 		context.rows = []
> ```

do not mutate the context here
___
*[`packages/engine-http/src/transfer/ContentImporter.ts` line 137 at r1](https://reviewable.io/reviews/contember/engine/285#-N3tBymu8w19cbXiJR5V:-N3tBymu8w19cbXiJR5W:bb7pa6j) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentImporter.ts#L137)):*
> ```XML
> 	private buildColumnRuntimeType(columnType: Model.ColumnType): Typesafe.Type<Exclude<Cell, null>> {
> 		switch (columnType) {
> 			case Model.ColumnType.Uuid: return Typesafe.string // TODO
> ```

todo
___
*[`packages/engine-http/src/transfer/PgSchemaBuilder.ts` line 3 at r1](https://reviewable.io/reviews/contember/engine/285#-N3szJEe67-ygq5Uy5UR:-N3szJEfBHRq9U9rOOlX:be70cjh) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/PgSchemaBuilder.ts#L3)):*
> ```XML
> import { Model, Schema } from '@contember/schema'
> import { acceptFieldVisitor } from '@contember/schema-utils'
> import Entity = Model.Entity
> ```

do not use import type aliases
___
*[`packages/engine-http/src/transfer/PgSchemaBuilder.ts` line 12 at r1](https://reviewable.io/reviews/contember/engine/285#-N3szBVk-Ix0rxQI6uOE:-N3szBVk-Ix0rxQI6uOF:bmcrdzp) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/PgSchemaBuilder.ts#L12)):*
> ```XML
> export type PgColumnSchema = { name: string, type: ColumnType, nullable: boolean }
> 
> export class PgSchemaBuilder {
> ```

please consider different prefix than Pg, e.g. Db
___
*[`packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts` line 20 at r1](https://reviewable.io/reviews/contember/engine/285#-N3t-66N-W3zOQ9zuVmF:-N3t-66OEo5Gf8Wvd6Jv:b-z8vwo1) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts#L20)):*
> ```XML
> 		private readonly debug: boolean,
> 		private readonly projectGroupResolver: ProjectGroupResolver,
> 		private readonly contentImporter: ContentImporter,
> ```

please split into two middleware factory classes
___
*[`packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts` line 35 at r1](https://reviewable.io/reviews/contember/engine/285#-N3szpnM0dSLev5SWxpV:-N3szpnM0dSLev5SWxpW:ba7rjwi) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts#L35)):*
> ```XML
> 			koaContext.state.authResult = authResult
> 
> 			if (!authResult.roles.includes('superadmin')) {
> ```

its called super_admin. and you should probably use TenantRole. and I think it should also be allowed for project_admin role
___
*[`packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts` line 36 at r1](https://reviewable.io/reviews/contember/engine/285#-N3szdGD7gA6RSIpbECs:-N3szdGD7gA6RSIpbECt:bvx3pvg) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts#L36)):*
> ```XML
> 
> 			if (!authResult.roles.includes('superadmin')) {
> 				// TODO
> ```

todo return 403
___
*[`packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts` line 62 at r1](https://reviewable.io/reviews/contember/engine/285#-N3t-K7B00jC_l3QsXTO:-N3t-K7B00jC_l3QsXTP:b-60dxw7) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts#L62)):*
> ```XML
> 				koaContext.compress = true
> 				response.status = 200
> 				response.headers['Content-Type'] = 'application/x-ndjson'
> ```

pls describe this content type (by linking relevant document/rfc/...)
___
*[`packages/engine-server/src/MasterContainer.ts` line 162 at r1](https://reviewable.io/reviews/contember/engine/285#-N3t-Vpr9YrBUeVtGEQe:-N3t-Vpr9YrBUeVtGEQf:bmhnrn1) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-server/src/MasterContainer.ts#L162)):*
> ```XML
> 					),
> 					route(
> 						'/export/:projectSlug/:stageSlug$',
> ```

i think we only want `/export` and `/import` routes and specify all parameters in post request

**Review by JanTvrdik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/285)* status: 4 of 15 files reviewed, 17 unresolved discussions (waiting on @JanTvrdik and @matej21)

___
*[`packages/engine-http/src/transfer/ContentExporter.ts` line 3 at r1](https://reviewable.io/reviews/contember/engine/285#-N3sw4Dj3_3Jfbtnua9n:-N42JwDm5rSM-y3i-e3Y:b-896fix) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentExporter.ts#L3)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

we don't use `.js` imports in engine (yet)
</blockquote></details>

Done.
___
*[`packages/engine-http/src/transfer/ContentExporter.ts` line 5 at r1](https://reviewable.io/reviews/contember/engine/285#-N3sygfFCcXRKRxUS7vm:-N42KdinA0X_hrC7u-6D:b-896fix) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentExporter.ts#L5)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

please do not use this import type aliases
</blockquote></details>

Done.
___
*[`packages/engine-http/src/transfer/ContentExporter.ts` line 7 at r1](https://reviewable.io/reviews/contember/engine/285#-N3t0RNMDIep9hFW3oEC:-N42L-3WAxTQO6Wta5J5:b-896fix) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentExporter.ts#L7)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

todo
</blockquote></details>

Done.
___
*[`packages/engine-http/src/transfer/ContentExporter.ts` line 19 at r1](https://reviewable.io/reviews/contember/engine/285#-N3syqtU1AUzb1PbvQGM:-N42MC583hkva8rslVAr:b-896fix) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentExporter.ts#L19)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

move this to database as a utility function
</blockquote></details>

Done.
___
*[`packages/engine-http/src/transfer/ContentExporter.ts` line 40 at r1](https://reviewable.io/reviews/contember/engine/285#-N3sz0cZDmqH9iJUc80F:-N42Np3J6jz_T4kWtTEB:b-896fix) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentExporter.ts#L40)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

isn't it possible to create this new-line buffer just once?
</blockquote></details>

Done.
___
*[`packages/engine-http/src/transfer/ContentExporter.ts` line 57 at r1](https://reviewable.io/reviews/contember/engine/285#-N3t6_FEA9V7Qt9m5tRW:-N42dKZv9wvqutGHReTc:bsotbp6) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentExporter.ts#L57)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

isn't 100 too low? have you tried some benchmarks?
</blockquote></details>

It's a good compromise between memory usage and performance. Using 500 is slightly faster but I assume would use 5x more memory.
___
*[`packages/engine-http/src/transfer/ContentImporter.ts` line 46 at r1](https://reviewable.io/reviews/contember/engine/285#-N3tAta95Npado2GA9KM:-N42P6TgCGktcLf1BaxA:b-896fix) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentImporter.ts#L46)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

this will cause internal server error 500, right? it needs to be handled.
</blockquote></details>

Done.
___
*[`packages/engine-http/src/transfer/ContentImporter.ts` line 103 at r1](https://reviewable.io/reviews/contember/engine/285#-N3tBVnY8L4XS6MADvz7:-N42PO274SqkZqt8IaWj:b-896fix) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/ContentImporter.ts#L103)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

do not mutate the context here
</blockquote></details>

Done.
___
*[`packages/engine-http/src/transfer/PgSchemaBuilder.ts` line 3 at r1](https://reviewable.io/reviews/contember/engine/285#-N3szJEe67-ygq5Uy5UR:-N42PPS858NZJ0BMefGN:b-896fix) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/PgSchemaBuilder.ts#L3)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

do not use import type aliases
</blockquote></details>

Done.
___
*[`packages/engine-http/src/transfer/PgSchemaBuilder.ts` line 12 at r1](https://reviewable.io/reviews/contember/engine/285#-N3szBVk-Ix0rxQI6uOE:-N42PpZV6yzhqA0DnGTI:b-896fix) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/PgSchemaBuilder.ts#L12)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

please consider different prefix than Pg, e.g. Db
</blockquote></details>

Done.
___
*[`packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts` line 35 at r1](https://reviewable.io/reviews/contember/engine/285#-N3szpnM0dSLev5SWxpV:-N42Rn4t7yJir3YxizOo:b-896fix) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts#L35)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

its called super_admin. and you should probably use TenantRole. and I think it should also be allowed for project_admin role
</blockquote></details>

Done.
___
*[`packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts` line 36 at r1](https://reviewable.io/reviews/contember/engine/285#-N3szdGD7gA6RSIpbECs:-N42Rmve8VnKY36LXOA9:b-896fix) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts#L36)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

todo return 403
</blockquote></details>

Done.
___
*[`packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts` line 62 at r1](https://reviewable.io/reviews/contember/engine/285#-N3t-K7B00jC_l3QsXTO:-N42QPJL0ilkX4EdgZzi:b-896fix) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts#L62)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

pls describe this content type (by linking relevant document/rfc/...)
</blockquote></details>

Done.
___
*[`packages/engine-server/src/MasterContainer.ts` line 162 at r1](https://reviewable.io/reviews/contember/engine/285#-N3t-Vpr9YrBUeVtGEQe:-N42QV78843t4QnBx_VX:b-yecdn4) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-server/src/MasterContainer.ts#L162)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

i think we only want `/export` and `/import` routes and specify all parameters in post request
</blockquote></details>

we can for sure do it for export, but it's harder to make it for import

**Review by JanTvrdik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/285)* status: 1 of 22 files reviewed, 17 unresolved discussions (waiting on @JanTvrdik and @matej21)

___
*[`packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts` line 20 at r1](https://reviewable.io/reviews/contember/engine/285#-N3t-66N-W3zOQ9zuVmF:-N4XOYhNAN8EtMTRXAqL:b-896fix) ([raw file](https://github.com/contember/engine/blob/4d90d51d769221f20750665b7eaec246771d9c88/packages/engine-http/src/transfer/TransferApiMiddlewareFactory.ts#L20)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

please split into two middleware factory classes
</blockquote></details>

Done.

**Review by matej21 — CHANGES_REQUESTED** [review]
> Reviewed 20 of 21 files at r2, 1 of 3 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/285)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @JanTvrdik)

___
*[`packages/engine-http/src/transfer/ImportApiMiddlewareFactory.ts` line 48 at r4](https://reviewable.io/reviews/contember/engine/285#-N4gEbJP9bpHSljuh7uR:-N4gEbJP9bpHSljuh7uS:bv4sgmo) ([raw file](https://github.com/contember/engine/blob/085ce5bcfee0d238bd34a3bbfaff0bec60845e97/packages/engine-http/src/transfer/ImportApiMiddlewareFactory.ts#L48)):*
> ```XML
> 			const commands = fromBuffer(isGzip ? request.req.pipe(createGunzip()) : request.req)
> 
> 			koaContext.compress = true
> ```

imho useless
___
*[`packages/engine-http/src/transfer/TransferMapping.ts` line 25 at r4](https://reviewable.io/reviews/contember/engine/285#-N4gEZ0pEpfYYGFmq-AJ:-N4gEZ0pEpfYYGFmq-AK:bb7pa6j) ([raw file](https://github.com/contember/engine/blob/085ce5bcfee0d238bd34a3bbfaff0bec60845e97/packages/engine-http/src/transfer/TransferMapping.ts#L25)):*
> ```XML
> 	| { name: string; nullable?: boolean; type: Model.ColumnType.Enum; values: readonly string[] }
> 
> // TODO: content sequence
> ```

todo

**Review by matej21 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/285)* status: 22 of 23 files reviewed, 5 unresolved discussions (waiting on @JanTvrdik and @matej21)

___
*[`-- commits` line 56 at r5](https://reviewable.io/reviews/contember/engine/285#-N54JtI09AFilXtlzWbk):*
typo, missing "s" in transfer
___
*[`-- commits` line 62 at r5](https://reviewable.io/reviews/contember/engine/285#-N54JsEw13J7SnpG3S4E):*
wrong scope
___
*[`packages/engine-http/src/transfer/ExportExecutor.ts` line 10 at r5](https://reviewable.io/reviews/contember/engine/285#-N54IosUDJCtc6A0e6a_:-N54IosUDJCtc6A0e6aa:b-6h6vf5) ([raw file](https://github.com/contember/engine/blob/6295507af47a8f3bcd90342c6bf0eb0dd629991b/packages/engine-http/src/transfer/ExportExecutor.ts#L10)):*
> ```XML
> import { StagesQuery } from '@contember/engine-system-api'
> import { ProjectContainer } from '../ProjectContainer'
> import ColumnType = Model.ColumnType
> ```

no import alias
___
*[`packages/engine-http/src/transfer/ExportExecutor.ts` line 74 at r5](https://reviewable.io/reviews/contember/engine/285#-N54JGdk7QbS6YVJfYrs:-N54JGdk7QbS6YVJfYrt:b-ql7g08) ([raw file](https://github.com/contember/engine/blob/6295507af47a8f3bcd90342c6bf0eb0dd629991b/packages/engine-http/src/transfer/ExportExecutor.ts#L74)):*
> ```XML
> 			if (column.type === ColumnType.Int && column.sequence) {
> 				const seqResult = await db.query<{ nextval: number }>(
> 					'SELECT nextval(pg_get_serial_sequence(?, ?))',
> ```

nextval increments sequence, causing a side effect.  currval is imho better (also, please set column alias explicitly)

**Review by JanTvrdik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/285)* status: 22 of 23 files reviewed, 4 unresolved discussions (waiting on @matej21)

___
*[`-- commits` line 62 at r5](https://reviewable.io/reviews/contember/engine/285#-N54JsEw13J7SnpG3S4E):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

wrong scope
</blockquote></details>

Done.
___
*[`packages/engine-http/src/transfer/ExportExecutor.ts` line 10 at r5](https://reviewable.io/reviews/contember/engine/285#-N54IosUDJCtc6A0e6a_:-N54Km7BBpG2R1Nug0Fa:b-896fix) ([raw file](https://github.com/contember/engine/blob/6295507af47a8f3bcd90342c6bf0eb0dd629991b/packages/engine-http/src/transfer/ExportExecutor.ts#L10)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

no import alias
</blockquote></details>

Done.
___
*[`packages/engine-http/src/transfer/ExportExecutor.ts` line 74 at r5](https://reviewable.io/reviews/contember/engine/285#-N54JGdk7QbS6YVJfYrs:-N54Knyl543NmrVhvzzt:b-1mupej) ([raw file](https://github.com/contember/engine/blob/6295507af47a8f3bcd90342c6bf0eb0dd629991b/packages/engine-http/src/transfer/ExportExecutor.ts#L74)):*
 currval does not work

> Error in query (7): ERROR: currval of sequence "seq_entity_id_seq" is not yet defined in this session
___
*[`packages/engine-http/src/transfer/TransferMapping.ts` line 25 at r4](https://reviewable.io/reviews/contember/engine/285#-N4gEZ0pEpfYYGFmq-AJ:-N54L1O15zTQeqdER2wN:b-896fix) ([raw file](https://github.com/contember/engine/blob/085ce5bcfee0d238bd34a3bbfaff0bec60845e97/packages/engine-http/src/transfer/TransferMapping.ts#L25)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

todo
</blockquote></details>

Done.

**Review by matej21 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/285)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanTvrdik)

**Pull request merged**
