### PR TITLE
Content API: assume role

### PR DESCRIPTION
**Pull request by matej21**
This change is [Reviewable](https://reviewable.io/reviews/contember/engine/270)

### CODE REVIEW

**Review by VojtaStanek — CHANGES_REQUESTED** [review]
> Reviewed 3 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/270)* status: 3 of 17 files reviewed, 2 unresolved discussions (waiting on @matej21 and @VojtaStanek)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/contember/engine/270#-N1Jb0cC2T9om-eaoSTr):*




_Suggestion:_
```
{memberships: {role: string, variables: {name: string, values: string[]}[]}
```
___
*[`packages/engine-http/src/content/ContentApiMiddlewareFactory.ts` line 63 at r1](https://reviewable.io/reviews/contember/engine/270#-N1Jb7gDEgcE1tIXABCU:-N1Jb7gDEgcE1tIXABCV:b7asri7) ([raw file](https://github.com/contember/engine/blob/e0e332d8050b37d182563cd2b6d249967da11579/packages/engine-http/src/content/ContentApiMiddlewareFactory.ts#L63)):*
> ```XML
> 			const schema = await projectContainer.contentSchemaResolver.getSchema(systemDatabase, stage.slug)
> 
> 			const memberships = await await timer('MembershipFetch', () => groupContainer.projectMembershipResolver.resolveMemberships({
> ```

too much (a)waiting

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/270)* status: 2 of 19 files reviewed, 2 unresolved discussions (waiting on @matej21 and @VojtaStanek)

___
*[`packages/engine-http/src/content/ContentApiMiddlewareFactory.ts` line 63 at r1](https://reviewable.io/reviews/contember/engine/270#-N1Jb7gDEgcE1tIXABCU:-N1dGUvm8mLj9yFeH7TA:b-896fix) ([raw file](https://github.com/contember/engine/blob/e0e332d8050b37d182563cd2b6d249967da11579/packages/engine-http/src/content/ContentApiMiddlewareFactory.ts#L63)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

too much (a)waiting
</blockquote></details>

Done.

**Review by VojtaStanek — CHANGES_REQUESTED** [review]
> Reviewed 11 of 17 files at r1, 3 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/270)* status: all files reviewed, 2 unresolved discussions (waiting on @matej21)

___
*[`packages/engine-http/src/content/ProjectMembershipResolver.ts` line 33 at r3](https://reviewable.io/reviews/contember/engine/270#-N1n45UM4YquwBIKrf2c:-N1n45UM4YquwBIKrf2d:b-z5yyy7) ([raw file](https://github.com/contember/engine/blob/011f03e27c0da6660332a91b7faad2970d6d131d/packages/engine-http/src/content/ProjectMembershipResolver.ts#L33)):*
> ```XML
> 		if (explicitMemberships.length === 0 && implicitRoles.length === 0) {
> 			throw this.debug
> 				? new HttpError(`You are not allowed to access project ${projectSlug}`, 403)
> ```

The status code is part of the API and shouldn't change based on the environment
___
*[`packages/engine-tenant-api/src/model/authorization/MembershipMatcher.ts` line 24 at r3](https://reviewable.io/reviews/contember/engine/270#-N1n64FH56Qy9Uj2MbpY:-N1n64FH56Qy9Uj2MbpZ:bdaym65) ([raw file](https://github.com/contember/engine/blob/011f03e27c0da6660332a91b7faad2970d6d131d/packages/engine-tenant-api/src/model/authorization/MembershipMatcher.ts#L24)):*
> ```XML
> 				return true
> 			}
> 			for (const variable of membership.variables) {
> ```

I find this nested for loops with different continues unreadable. why not something like `membership.variables.every(variable => {...})`?

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/270)* status: 15 of 20 files reviewed, 2 unresolved discussions (waiting on @VojtaStanek)

___
*[`packages/engine-http/src/content/ProjectMembershipResolver.ts` line 33 at r3](https://reviewable.io/reviews/contember/engine/270#-N1n45UM4YquwBIKrf2c:-N1nAcWbAfBMLxAJYJmK:b-896fix) ([raw file](https://github.com/contember/engine/blob/011f03e27c0da6660332a91b7faad2970d6d131d/packages/engine-http/src/content/ProjectMembershipResolver.ts#L33)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

The status code is part of the API and shouldn't change based on the environment
</blockquote></details>

Done.
___
*[`packages/engine-tenant-api/src/model/authorization/MembershipMatcher.ts` line 24 at r3](https://reviewable.io/reviews/contember/engine/270#-N1n64FH56Qy9Uj2MbpY:-N1s7EemAaBb1Y7mLKVK:b-896fix) ([raw file](https://github.com/contember/engine/blob/011f03e27c0da6660332a91b7faad2970d6d131d/packages/engine-tenant-api/src/model/authorization/MembershipMatcher.ts#L24)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

I find this nested for loops with different continues unreadable. why not something like `membership.variables.every(variable => {...})`?
</blockquote></details>

Done.

**Review by VojtaStanek — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/270)* status: all files reviewed, 1 unresolved discussion (waiting on @matej21)

___
*[`packages/engine-tenant-api/src/model/authorization/MembershipMatcher.ts` line 27 at r4](https://reviewable.io/reviews/contember/engine/270#-N1sA_nR0PN3EIbt9kLM:-N1sA_nR0PN3EIbt9kLN:bpp6stj) ([raw file](https://github.com/contember/engine/blob/9ad04574e2e65889af60b3f4f064a5ba180e311e/packages/engine-tenant-api/src/model/authorization/MembershipMatcher.ts#L27)):*
> ```XML
> 				return true
> 			}
> 			if (!variables) {
> ```

not needed

**Pull request merged**
