### PR TITLE
feat(engine): default order on entity level

### PR DESCRIPTION
**Pull request by dodolab**
This change is [Reviewable](https://reviewable.io/reviews/contember/engine/373)

### CODE REVIEW

**Review by matej21 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/373)* status: 12 of 14 files reviewed, 7 unresolved discussions (waiting on @dodolab)

___
*[`packages/schema-definition/src/model/builder/EntityBuilder.ts` line 97 at r1](https://reviewable.io/reviews/contember/engine/373#-NOPmxp82o2LMSCpcKJm:-NOPmxp82o2LMSCpcKJn:bpivubt) ([raw file](https://github.com/contember/engine/blob/ae42527f7a56565f1bcbe24b970af4c842c6d2a2/packages/schema-definition/src/model/builder/EntityBuilder.ts#L97)):*
> ```XML
> 
> 		return new EntityBuilder(
> 			{ ...this.options, orderBy: [...(this.options.orderBy || []), { path, direction }] },
> ```

use `??` instead of `||`
___
*[`packages/schema-definition/src/model/definition/OrderByDefinition.ts` line 8 at r1](https://reviewable.io/reviews/contember/engine/373#-NOPmGHXAcWUfzR9DdJB:-NOPmGHYDC3GQBbT2v1d:b-dxxvj6) ([raw file](https://github.com/contember/engine/blob/ae42527f7a56565f1bcbe24b970af4c842c6d2a2/packages/schema-definition/src/model/definition/OrderByDefinition.ts#L8)):*
> ```XML
> export type OrderByOptions = { path: string[]; direction?: Model.OrderDirection }
> 
> export function OrderBy<T>(path: (keyof T), direction: Model.OrderDirection): DecoratorFunction<T>
> ```

- "direction" parameter should be optional here
- signature for "OrderByOptions" variant is missing
___
*[`packages/schema-definition/src/model/definition/OrderByDefinition.ts` line 15 at r1](https://reviewable.io/reviews/contember/engine/373#-NOPmldI33OytHJVOv1f:-NOPmldI33OytHJVOv1g:b1e95ud) ([raw file](https://github.com/contember/engine/blob/ae42527f7a56565f1bcbe24b970af4c842c6d2a2/packages/schema-definition/src/model/definition/OrderByDefinition.ts#L15)):*
> ```XML
> 			((typeof options === 'object' && options.direction)
> 				? options.direction
> 				: direction) || Model.OrderDirection.asc
> ```

`??` is usually preferred
___
*[`packages/schema-definition/src/model/definition/OrderByDefinition.ts` line 20 at r1](https://reviewable.io/reviews/contember/engine/373#-NOPn5Yl0dfKfqsZW4zf:-NOPn5Yl0dfKfqsZW4zg:bq0pte7) ([raw file](https://github.com/contember/engine/blob/ae42527f7a56565f1bcbe24b970af4c842c6d2a2/packages/schema-definition/src/model/definition/OrderByDefinition.ts#L20)):*
> ```XML
> 		return {
> 			...entity,
> 			orderBy: entity.orderBy ? [...entity.orderBy, ...[{
> ```

replace the ternary operator with the same expression you use in EntityBuilder 
```
orderBy: [...entity.orderBy ?? [], {path, direction: dir}]
```
___
*[`packages/schema-migrations/src/modifications/entities/UpdateEntityOrderByModification.ts` line 49 at r1](https://reviewable.io/reviews/contember/engine/373#-NOPnRzn5QXe7IuE-CfW:-NOPnRzn5QXe7IuE-CfX:bfg7tj4) ([raw file](https://github.com/contember/engine/blob/ae42527f7a56565f1bcbe24b970af4c842c6d2a2/packages/schema-migrations/src/modifications/entities/UpdateEntityOrderByModification.ts#L49)):*
> ```XML
> 
> 				if (!deepEqual(updatedEntity.orderBy || [], origEntity.orderBy || [])
> 				) {
> ```

there should not be a line break before `)`
___
*[`packages/schema-migrations/src/modifications/entities/UpdateEntityOrderByModification.ts` line 52 at r1](https://reviewable.io/reviews/contember/engine/373#-NOPnWBi1Q-q1OtVgQTM:-NOPnWBi1Q-q1OtVgQTN:bb7bhyd) ([raw file](https://github.com/contember/engine/blob/ae42527f7a56565f1bcbe24b970af4c842c6d2a2/packages/schema-migrations/src/modifications/entities/UpdateEntityOrderByModification.ts#L52)):*
> ```XML
> 					return [updateEntityOrderByModification.createModification({
> 						entityName: updatedEntity.name,
> 						orderBy: updatedEntity.orderBy || [],
> ```

`??`
___
*[`packages/schema-migrations/tests/cases/integration/updateEntityOrderBy.test.ts` line 20 at r1](https://reviewable.io/reviews/contember/engine/373#-NOPncuO21lYAd7KQuUC:-NOPncuO21lYAd7KQuUD:b-iad6ua) ([raw file](https://github.com/contember/engine/blob/ae42527f7a56565f1bcbe24b970af4c842c6d2a2/packages/schema-migrations/tests/cases/integration/updateEntityOrderBy.test.ts#L20)):*
> ```XML
> }
> 
> testMigrations('update entity order by', {
> ```

please add a test for an opposite case, when a orderBy is removed. I think it may not work correctly, because the migration handler will create an empty `[]` array

**Review by dodolab — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/373)* status: 9 of 14 files reviewed, 7 unresolved discussions (waiting on @matej21)

___
*[`packages/schema-definition/src/model/builder/EntityBuilder.ts` line 97 at r1](https://reviewable.io/reviews/contember/engine/373#-NOPmxp82o2LMSCpcKJm:-NOPua8Y5p1XtuLRmm_s:b-896fix) ([raw file](https://github.com/contember/engine/blob/ae42527f7a56565f1bcbe24b970af4c842c6d2a2/packages/schema-definition/src/model/builder/EntityBuilder.ts#L97)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

use `??` instead of `||`
</blockquote></details>

Done.
___
*[`packages/schema-definition/src/model/definition/OrderByDefinition.ts` line 8 at r1](https://reviewable.io/reviews/contember/engine/373#-NOPmGHXAcWUfzR9DdJB:-NOPu_PJ90t5UzCxkTKg:b-896fix) ([raw file](https://github.com/contember/engine/blob/ae42527f7a56565f1bcbe24b970af4c842c6d2a2/packages/schema-definition/src/model/definition/OrderByDefinition.ts#L8)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

- "direction" parameter should be optional here
- signature for "OrderByOptions" variant is missing
</blockquote></details>

Done.
___
*[`packages/schema-definition/src/model/definition/OrderByDefinition.ts` line 15 at r1](https://reviewable.io/reviews/contember/engine/373#-NOPmldI33OytHJVOv1f:-NOPu_9l-QTPK2YZYeBT:b-896fix) ([raw file](https://github.com/contember/engine/blob/ae42527f7a56565f1bcbe24b970af4c842c6d2a2/packages/schema-definition/src/model/definition/OrderByDefinition.ts#L15)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

`??` is usually preferred
</blockquote></details>

Done.
___
*[`packages/schema-definition/src/model/definition/OrderByDefinition.ts` line 20 at r1](https://reviewable.io/reviews/contember/engine/373#-NOPn5Yl0dfKfqsZW4zf:-NOPuZnpAHFz-Vgr3RX-:b-896fix) ([raw file](https://github.com/contember/engine/blob/ae42527f7a56565f1bcbe24b970af4c842c6d2a2/packages/schema-definition/src/model/definition/OrderByDefinition.ts#L20)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

replace the ternary operator with the same expression you use in EntityBuilder 
```
orderBy: [...entity.orderBy ?? [], {path, direction: dir}]
```
</blockquote></details>

Done.
___
*[`packages/schema-migrations/src/modifications/entities/UpdateEntityOrderByModification.ts` line 49 at r1](https://reviewable.io/reviews/contember/engine/373#-NOPnRzn5QXe7IuE-CfW:-NOPuYJ73BevVoogqwAA:bb7f2mf) ([raw file](https://github.com/contember/engine/blob/ae42527f7a56565f1bcbe24b970af4c842c6d2a2/packages/schema-migrations/src/modifications/entities/UpdateEntityOrderByModification.ts#L49)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

there should not be a line break before `)`
</blockquote></details>

done
___
*[`packages/schema-migrations/src/modifications/entities/UpdateEntityOrderByModification.ts` line 52 at r1](https://reviewable.io/reviews/contember/engine/373#-NOPnWBi1Q-q1OtVgQTM:-NOPuXEP6IqCk977PFhg:bb7f2mf) ([raw file](https://github.com/contember/engine/blob/ae42527f7a56565f1bcbe24b970af4c842c6d2a2/packages/schema-migrations/src/modifications/entities/UpdateEntityOrderByModification.ts#L52)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

`??`
</blockquote></details>

done
___
*[`packages/schema-migrations/tests/cases/integration/updateEntityOrderBy.test.ts` line 20 at r1](https://reviewable.io/reviews/contember/engine/373#-NOPncuO21lYAd7KQuUC:-NOPuOZ31DWPgqnysLZ9:b477xf8) ([raw file](https://github.com/contember/engine/blob/ae42527f7a56565f1bcbe24b970af4c842c6d2a2/packages/schema-migrations/tests/cases/integration/updateEntityOrderBy.test.ts#L20)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

please add a test for an opposite case, when a orderBy is removed. I think it may not work correctly, because the migration handler will create an empty `[]` array
</blockquote></details>

It didn't. I fixed it in the handler

**Review by matej21 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/373)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dodolab)

**Comment by matej21** [comment]
merged in #381

**Pull request closed without merging**
