### PR TITLE
ACL definition using decorators

### PR DESCRIPTION
**Pull request by matej21**
This change is [Reviewable](https://reviewable.io/reviews/contember/engine/253)

### CODE REVIEW

**Review by VojtaStanek — CHANGES_REQUESTED** [review]
> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/253)* status: all files reviewed, 13 unresolved discussions (waiting on @matej21)

___
*[packages/cli-common/resources/templates/template-project/api/index.ts, line 9 at r1](https://reviewable.io/reviews/contember/engine/253#-N06asJGEoqprUxJZ65H:-N06asJGEoqprUxJZ65I:b-u7vj8i) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/cli-common/resources/templates/template-project/api/index.ts#L9)):*
> ```XML
> 		acl: {
> 			...schema.acl,
> 			customPrimary: true,
> ```

I wouldn't do that
___
*[packages/schema-definition/src/index.ts, line 10 at r1](https://reviewable.io/reviews/contember/engine/253#-N06TAPJ2Rm5Tvk4OA2X:-N06TAPJ2Rm5Tvk4OA2Y:b-wdf373) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/index.ts#L10)):*
> ```XML
> export * from './model'
> 
> export const createSchema = (definitions: Record<string, any>, modifyCallback?: (schema: Schema) => Schema): Schema => {
> ```

minor: I had problems to find it here, I would suggest moving it into seperete file. 
___
*[packages/schema-definition/src/acl/definition/index.ts, line 21 at r1](https://reviewable.io/reviews/contember/engine/253#-N06Xkcs-2IX-6zQsH11:-N06Xkct8p7t3wKsGtNI:b9j5m8u) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/index.ts#L21)):*
> ```XML
> 
> ```

nit: newline party here...
___
*[packages/schema-definition/src/acl/definition/internal/AclFactory.ts, line 59 at r1](https://reviewable.io/reviews/contember/engine/253#-N06iGE29AOS4KDSfnP0:-N06iGE35CSbvk4Wy-JJ:b-u24ntl) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/AclFactory.ts#L59)):*
> ```XML
> 				const fieldPermissions: Writable<Acl.FieldPermissions> = {}
> 				for (const field of Object.keys(entity.fields)) {
> 					if (field === entity.primary) {
> ```

Can I create custom permissions for primary?
___
*[packages/schema-definition/src/acl/definition/internal/AclFactory.ts, line 95 at r1](https://reviewable.io/reviews/contember/engine/253#-N06buSp5BAhrnHavCiP:-N06buSp5BAhrnHavCiQ:undefined) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/AclFactory.ts#L95)):*
> ```XML
> 	}
> 
> 	private static groupPermissions (entityLikeDefinition: [string, { new(): any }][], roles: Role[]): PermissionsByRoleAndEntity {
> ```





_Suggestion:_
```XML
	private static groupPermissions(entityLikeDefinition: [string, { new(): any }][], roles: Role[]): PermissionsByRoleAndEntity {
```
___
*[packages/schema-definition/src/acl/definition/internal/AclFactory.ts, line 98 at r1](https://reviewable.io/reviews/contember/engine/253#-N06d0mv--mqmYlTOqcX:-N06d0mv--mqmYlTOqcY:boavssh) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/AclFactory.ts#L98)):*
> ```XML
> 		const groupedPermissions: PermissionsByRoleAndEntity = new Map()
> 		entityLikeDefinition
> 			.forEach(([name, entity]) => {
> ```

for-of!
___
*[packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts, line 17 at r1](https://reviewable.io/reviews/contember/engine/253#-N06imQt1YACmvqSUK-5:-N06imQt1YACmvqSUK-6:b-a63ygo) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts#L17)):*
> ```XML
> 	private constructor(
> 		private aclDefinitions: AllowDefinition<any>[],
> 		private _predicates: Writable<Acl.PredicateMap>,
> ```

why underscore?
___
*[packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts, line 31 at r1](https://reviewable.io/reviews/contember/engine/253#-N06jA1jEUxS9i1WTsJP:-N06jA1jEUxS9i1WTsJQ:b3es5iv) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts#L31)):*
> ```XML
> 		const predicateNamesMap = new Map<WhenDefinition, string>()
> 		const aclDefinitions = rolePermissions.get(entity.name)?.definitions ?? []
> 		const generatedNames = new Set<string>()
> ```

this set is always empty
___
*[packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts, line 39 at r1](https://reviewable.io/reviews/contember/engine/253#-N06jVo65RZXT4JPF6jT:-N06jVo73fieaAgJDDu_:b5786ri) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts#L39)):*
> ```XML
> 			let predicateName = permission.name ?? createPredicateName(resolvedPredicate)
> 			while (predicateName in predicates) {
> 				predicateName += '_'
> ```

This can override my custom name, I wouldn't expect that. 
___
*[packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts, line 95 at r1](https://reviewable.io/reviews/contember/engine/253#-N06lfU0-onSYDPBMYP2:-N06lfU0-onSYDPBMYP3:bkpa7im) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts#L95)):*
> ```XML
> 				}
> 				if (ctx.value instanceof PredicateEvaluationReference) {
> 					throw `Not allowed on column`
> ```

more user-friendly message
___
*[packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts, line 101 at r1](https://reviewable.io/reviews/contember/engine/253#-N06lsDn-LqimNBQ8Fmn:-N06lsDn-LqimNBQ8Fmo:bwxxjwi) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts#L101)):*
> ```XML
> 			handleRelation(ctx) {
> 				if (ctx.value instanceof EntityVariableDefinition) {
> 					return { [ctx.targetEntity.primary]: ctx.value.name }
> ```

Shouldn't this be explicit? 

Or: Shouldn't we assert that it's used on correct entity?
___
*[packages/schema-definition/src/model/definition/index.ts, line 22 at r1](https://reviewable.io/reviews/contember/engine/253#-N06ZvYw0UQ5JHxx49m5:-N06ZvYw0UQ5JHxx49m6:undefined) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/model/definition/index.ts#L22)):*
> ```XML
> 
> export type ModelDefinition<M> = {
> 	[K in keyof M]: any
> ```





_Suggestion:_
```XML
	[K in keyof M]: unknown
```
___
*[packages/schema-definition/src/utils/filterEntityDefinition.ts, line 6 at r1](https://reviewable.io/reviews/contember/engine/253#-N06a4HGBpn--liegCtT:-N06a4HGBpn--liegCtU:undefined) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/utils/filterEntityDefinition.ts#L6)):*
> ```XML
> 	.filter(it => isEntityConstructor(it[1]))
> 
> export const isEntityConstructor = (it: any): it is EntityConstructor => {
> ```





_Suggestion:_
```XML
export const isEntityConstructor = (it: unknown): it is EntityConstructor => {
```

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/253)* status: 25 of 38 files reviewed, 11 unresolved discussions (waiting on @VojtaStanek)

___
*[`packages/cli-common/resources/templates/template-project/api/index.ts` line 9 at r1](https://reviewable.io/reviews/contember/engine/253#-N06asJGEoqprUxJZ65H:-N0UhOk32DPp0VRQiiy9:b-896fix) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/cli-common/resources/templates/template-project/api/index.ts#L9)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

I wouldn't do that
</blockquote></details>

Done.
___
*[`packages/schema-definition/src/acl/definition/internal/AclFactory.ts` line 59 at r1](https://reviewable.io/reviews/contember/engine/253#-N06iGE29AOS4KDSfnP0:-N0UiUvHBf5S6ZsSvL2p:bx9b0lv) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/AclFactory.ts#L59)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

Can I create custom permissions for primary?
</blockquote></details>

no, its always OR of field permissions
___
*[`packages/schema-definition/src/acl/definition/internal/AclFactory.ts` line 95 at r1](https://reviewable.io/reviews/contember/engine/253#-N06buSp5BAhrnHavCiP:-N0Uj6yL5SlMnTj9s7TV:b-896fix) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/AclFactory.ts#L95)):*
> ```XML
> 	}
> 
> 	private static groupPermissions (entityLikeDefinition: [string, { new(): any }][], roles: Role[]): PermissionsByRoleAndEntity {
> ```

Done.
___
*[`packages/schema-definition/src/acl/definition/internal/AclFactory.ts` line 98 at r1](https://reviewable.io/reviews/contember/engine/253#-N06d0mv--mqmYlTOqcX:-N0Uj7D053Lw4Cbf6eW6:b-896fix) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/AclFactory.ts#L98)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

for-of!
</blockquote></details>

Done.
___
*[`packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts` line 17 at r1](https://reviewable.io/reviews/contember/engine/253#-N06imQt1YACmvqSUK-5:-N0UkAaV75cOrcQVeOw1:b-tp3lee) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts#L17)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

why underscore?
</blockquote></details>

there was a getter "predicates", I've changed it to "getUsedPredicates", so it is more explicit
___
*[`packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts` line 31 at r1](https://reviewable.io/reviews/contember/engine/253#-N06jA1jEUxS9i1WTsJP:-N0UjryH0EG0nV04q9Y9:b-896fix) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts#L31)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

this set is always empty
</blockquote></details>

Done.
___
*[`packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts` line 39 at r1](https://reviewable.io/reviews/contember/engine/253#-N06jVo65RZXT4JPF6jT:-N0UjsOj65K0KDlmX38r:bftl5yw) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts#L39)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

This can override my custom name, I wouldn't expect that. 
</blockquote></details>

Not probable, but done.
___
*[`packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts` line 95 at r1](https://reviewable.io/reviews/contember/engine/253#-N06lfU0-onSYDPBMYP2:-N0Ulxq42Tg2hhhObGRr:b-896fix) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts#L95)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

more user-friendly message
</blockquote></details>

Done.
___
*[`packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts` line 101 at r1](https://reviewable.io/reviews/contember/engine/253#-N06lsDn-LqimNBQ8Fmn:-N0Uk-FNAKbyFO57mVjH:bdowly0) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts#L101)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

Shouldn't this be explicit? 

Or: Shouldn't we assert that it's used on correct entity?
</blockquote></details>

that is a job of schema validator
___
*[`packages/schema-definition/src/model/definition/index.ts` line 22 at r1](https://reviewable.io/reviews/contember/engine/253#-N06ZvYw0UQ5JHxx49m5:-N0UmPNX0rZ7L1HMWE0Z:b-896fix) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/model/definition/index.ts#L22)):*
> ```XML
> 
> export type ModelDefinition<M> = {
> 	[K in keyof M]: any
> ```

Done.
___
*[`packages/schema-definition/src/utils/filterEntityDefinition.ts` line 6 at r1](https://reviewable.io/reviews/contember/engine/253#-N06a4HGBpn--liegCtT:-N0UmOrY0OhVcEX_ndw9:b-896fix) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/utils/filterEntityDefinition.ts#L6)):*
> ```XML
> 	.filter(it => isEntityConstructor(it[1]))
> 
> export const isEntityConstructor = (it: any): it is EntityConstructor => {
> ```

Done.

**Review by VojtaStanek — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/253)* status: all files reviewed, 3 unresolved discussions (waiting on @matej21 and @VojtaStanek)

___
*[`packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts` line 149 at r2](https://reviewable.io/reviews/contember/engine/253#-N0jITao9AlX5jnNap5z:-N0jITao9AlX5jnNap6-:bqb6ph6) ([raw file](https://github.com/contember/engine/blob/ff61c1bd4af4a880c5a9cc95cecdc6dc610498cb/packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts#L149)):*
> ```XML
> }
> 
> export const upperCaseFirst = (string: string) => `${string.charAt(0).toUpperCase()}${string.substring(1)}`
> ```

Either don't export it or move it to more suitable place.

**Review by VojtaStanek — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/253)* status: all files reviewed, 2 unresolved discussions (waiting on @matej21)

___
*[`packages/schema-definition/src/acl/definition/internal/AclFactory.ts` line 59 at r1](https://reviewable.io/reviews/contember/engine/253#-N06iGE29AOS4KDSfnP0:-N137EBb7s3FZYfWcTTJ:b44u2y) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/acl/definition/internal/AclFactory.ts#L59)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

no, its always OR of field permissions
</blockquote></details>

😢
___
*[`packages/schema-definition/src/utils/filterEntityDefinition.ts` line 6 at r1](https://reviewable.io/reviews/contember/engine/253#-N06a4HGBpn--liegCtT:-N133Wam-I8-N3B8lObX:b-8nyi3w) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/utils/filterEntityDefinition.ts#L6)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/253)* status: 37 of 38 files reviewed, 2 unresolved discussions (waiting on @VojtaStanek)

___
*[`packages/schema-definition/src/utils/filterEntityDefinition.ts` line 6 at r1](https://reviewable.io/reviews/contember/engine/253#-N06a4HGBpn--liegCtT:-N13YT0p7Sh4Kvh1AF3F:b-896fix) ([raw file](https://github.com/contember/engine/blob/36b41d23dd6925669bf8458a82d538393f341266/packages/schema-definition/src/utils/filterEntityDefinition.ts#L6)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Done.

**Pull request merged**
