### PR TITLE
refactor(content-api): condition optimizer

### PR DESCRIPTION
**Pull request by JanTvrdik**
This change is [Reviewable](https://reviewable.io/reviews/contember/engine/307)

### CODE REVIEW

**Review by matej21 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/307)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @JanTvrdik and @matej21)

___
*[`packages/engine-content-api/src/mapper/select/optimizer/helpers.ts` line 46 at r1](https://reviewable.io/reviews/contember/engine/307#-N8UhCsR6weD-TtHGN-a:-N8UhCsSEtC42bAd-FME:b18imi5) ([raw file](https://github.com/contember/engine/blob/3bedbe1ffd272b9fb5cf3dd02f8a03d39066aefd/packages/engine-content-api/src/mapper/select/optimizer/helpers.ts#L46)):*
> ```XML
> }
> 
> export const optimizeNot = <P extends object>(part: P | boolean): { not: P } | boolean => {
> ```

this is more like "createNot" or "normalizeNot"

**Review by JanTvrdik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/307)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @matej21)

___
*[`packages/engine-content-api/src/mapper/select/optimizer/helpers.ts` line 46 at r1](https://reviewable.io/reviews/contember/engine/307#-N8UhCsR6weD-TtHGN-a:-N8Un5Ly0uLVtg_dJfkD:bkgpo21) ([raw file](https://github.com/contember/engine/blob/3bedbe1ffd272b9fb5cf3dd02f8a03d39066aefd/packages/engine-content-api/src/mapper/select/optimizer/helpers.ts#L46)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

this is more like "createNot" or "normalizeNot"
</blockquote></details>

It symmetric to `optimizeAnd` and `optimizeOr`. All of them receive optimized operator operands as input and return either the created "operator node" (if there is nothing to optimize) or its "optimized version".

**Review by matej21 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/307)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @JanTvrdik and @matej21)

___
*[`packages/engine-content-api/src/mapper/select/optimizer/helpers.ts` line 46 at r1](https://reviewable.io/reviews/contember/engine/307#-N8UhCsR6weD-TtHGN-a:-N8UyL3OEwlezYReVzuw:b-2oy06i) ([raw file](https://github.com/contember/engine/blob/3bedbe1ffd272b9fb5cf3dd02f8a03d39066aefd/packages/engine-content-api/src/mapper/select/optimizer/helpers.ts#L46)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

It symmetric to `optimizeAnd` and `optimizeOr`. All of them receive optimized operator operands as input and return either the created "operator node" (if there is nothing to optimize) or its "optimized version".
</blockquote></details>

I know, but here, it is weird, because it optimizes nothing. Maybe rename everything to `normalize*`?

**Review by JanTvrdik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/307)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @matej21)

___
*[`packages/engine-content-api/src/mapper/select/optimizer/helpers.ts` line 46 at r1](https://reviewable.io/reviews/contember/engine/307#-N8UhCsR6weD-TtHGN-a:-N8VYOsx8lRDXPDNGrAF:bo6o135) ([raw file](https://github.com/contember/engine/blob/3bedbe1ffd272b9fb5cf3dd02f8a03d39066aefd/packages/engine-content-api/src/mapper/select/optimizer/helpers.ts#L46)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

I know, but here, it is weird, because it optimizes nothing. Maybe rename everything to `normalize*`?
</blockquote></details>

What you mean it optimizes nothing? It does optimize `{ not: true }` to `false` and it optimizes `{ not: false }` to `true`. 
But I'm aslo fine with renaming everything to `normalize*` if you think that would be better.

**Pull request merged**
