### PR TITLE
Migration improvements

### PR DESCRIPTION
**Pull request by matej21**
- migration executed using migrate mutation are idempotent
- advisory locks are acquired in migrate mutation

---
This change is [Reviewable](https://reviewable.io/reviews/contember/engine/294)

### CODE REVIEW

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/294)* status: 3 of 27 files reviewed, 2 unresolved discussions (waiting on @JanTvrdik)

___
*[`packages/engine-system-api/src/resolvers/mutation/MigrateMutationResolver.ts` line 32 at r1](https://reviewable.io/reviews/contember/engine/294#-N6OE6sv1OdNlhwZEa3f:-N6l_Zso0nXvsJBiUM2x:b-896fix) ([raw file](https://github.com/contember/engine/blob/aeb9c41b8c2016c9f820bea41fbb07cf80ee716e/packages/engine-system-api/src/resolvers/mutation/MigrateMutationResolver.ts#L32)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

If this is session level lock, it should be acquired before starting transaction.
</blockquote></details>

Done.
___
*[`packages/engine-system-api/src/resolvers/mutation/MigrateMutationResolver.ts` line 39 at r1](https://reviewable.io/reviews/contember/engine/294#-N6OER403kdPyJy---t9:-N6la4VAA2YVIkIllvnX:b-ln62df) ([raw file](https://github.com/contember/engine/blob/aeb9c41b8c2016c9f820bea41fbb07cf80ee716e/packages/engine-system-api/src/resolvers/mutation/MigrateMutationResolver.ts#L39)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

why supress logging?
</blockquote></details>

it was useful when migrations were executed during server startup, I've removed it completely.

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r2, 7 of 8 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/294)* status: all files reviewed, 6 unresolved discussions (waiting on @matej21)

___
*[`packages/database/src/client/AcquiredConnection.ts` line 71 at r2](https://reviewable.io/reviews/contember/engine/294#-N6lW2Bk6E7VsENKauRE:-N6lW2Bk6E7VsENKauRF:b7donzp) ([raw file](https://github.com/contember/engine/blob/b95548dba7891af6f5f3298442096ad9e295914b/packages/database/src/client/AcquiredConnection.ts#L71)):*
> ```XML
> 				let result: Connection.Result<Row>
> 				if (timing) {
> 					const startHrTime = process.hrtime()
> ```


___
*[`packages/database/src/client/Client.ts` line 27 at r2](https://reviewable.io/reviews/contember/engine/294#-N6lWu-J5THX4plWNChD:-N6lWu-J5THX4plWNChE:undefined) ([raw file](https://github.com/contember/engine/blob/b95548dba7891af6f5f3298442096ad9e295914b/packages/database/src/client/Client.ts#L27)):*
> ```XML
> 					new Client(
> 						connection,
> 						this.schema,
> ```





_Suggestion:_
```XML
			connection => callback(
				new Client(
					connection,
					this.schema,
					this.queryMeta,
					new EventManager(connection.eventManager),
				)),
```
___
*[`packages/database/src/client/Client.ts` line 51 at r4](https://reviewable.io/reviews/contember/engine/294#-N6li8Y84AThYyo9Cdwx:-N6li8Y84AThYyo9Cdwy:undefined) ([raw file](https://github.com/contember/engine/blob/3319b5c6adcf6c529ed52c5d623fc3a6d78f6eda/packages/database/src/client/Client.ts#L51)):*
> ```XML
> 
> 	async locked<T>(lock: number, callback: (wrapper: Client<Connection.ConnectionLike>) => Promise<T> | T): Promise<T> {
> 		return await this.scope(client =>
> ```





_Suggestion:_
```XML
		return await this.scope(client => withDatabaseAdvisoryLock(client.connection, lock, () => callback(client)))
```
___
*[`packages/database/src/client/Connection.ts` line 123 at r4](https://reviewable.io/reviews/contember/engine/294#-N6lj8ci9XciFRbu6cr4:-N6lj8cj6mHH_vBxNzGs:byjexne) ([raw file](https://github.com/contember/engine/blob/3319b5c6adcf6c529ed52c5d623fc3a6d78f6eda/packages/database/src/client/Connection.ts#L123)):*
> ```XML
> 			callback: (connection: Sub) => Promise<Result> | Result,
> 			options?: { eventManager?: EventManager },
> 		): Promise<Result>
> ```

This should probably be symetric with `Transactional`, meaning

* rename `ConnectionWithScope` to `Scopable`
* add `Sub` generic parameter to `Transactional`

also maybe `Transactional` should extend `Scopable`, as transactions require scope capability to be present
___
*[`packages/database/src/client/Connection.ts` line 137 at r4](https://reviewable.io/reviews/contember/engine/294#-N6ll9uJE-HurgjT6-1f:-N6ll9uJE-HurgjT6-1g:b-1cozl9) ([raw file](https://github.com/contember/engine/blob/3319b5c6adcf6c529ed52c5d623fc3a6d78f6eda/packages/database/src/client/Connection.ts#L137)):*
> ```XML
> 	}
> 
> 	export interface TransactionLike extends Transactional, Queryable, ConnectionWithScope<TransactionLike> {
> ```

This seem like semantic downgrade, it would be much better to instead add generic parameter to `ConnectionLike` extend `ConnectionLike<TransactionLike>`
___
*[`packages/engine-system-api/src/resolvers/mutation/MigrateMutationResolver.ts` line 43 at r4](https://reviewable.io/reviews/contember/engine/294#-N6lfZ3s3BdMK9TQKA87:-N6lfZ3s3BdMK9TQKA88:b-df63vq) ([raw file](https://github.com/contember/engine/blob/3319b5c6adcf6c529ed52c5d623fc3a6d78f6eda/packages/engine-system-api/src/resolvers/mutation/MigrateMutationResolver.ts#L43)):*
> ```XML
> 			} catch (e) {
> 				if (e instanceof MigrationError) {
> 					await trx.client.connection.rollback()
> ```

does manually rollbacking transaction not fucked up the state? why is that even allowed? why not rely on built-in rollback on throw?

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/294)* status: all files reviewed, 6 unresolved discussions (waiting on @JanTvrdik)

___
*[`packages/database/src/client/AcquiredConnection.ts` line 71 at r2](https://reviewable.io/reviews/contember/engine/294#-N6lW2Bk6E7VsENKauRE:-N6mIhohAl4zMj2vj-T2:b-896fix) ([raw file](https://github.com/contember/engine/blob/b95548dba7891af6f5f3298442096ad9e295914b/packages/database/src/client/AcquiredConnection.ts#L71)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>


</blockquote></details>

Done.
___
*[`packages/database/src/client/Client.ts` line 27 at r2](https://reviewable.io/reviews/contember/engine/294#-N6lWu-J5THX4plWNChD:-N6mJ-4X8d7gd8-dZ6zn:b-896fix) ([raw file](https://github.com/contember/engine/blob/b95548dba7891af6f5f3298442096ad9e295914b/packages/database/src/client/Client.ts#L27)):*
> ```XML
> 					new Client(
> 						connection,
> 						this.schema,
> ```

Done.
___
*[`packages/database/src/client/Client.ts` line 51 at r4](https://reviewable.io/reviews/contember/engine/294#-N6li8Y84AThYyo9Cdwx:-N6mJ0XR0wfb4enVNTmE:b32wsm) ([raw file](https://github.com/contember/engine/blob/3319b5c6adcf6c529ed52c5d623fc3a6d78f6eda/packages/database/src/client/Client.ts#L51)):*
> ```XML
> 
> 	async locked<T>(lock: number, callback: (wrapper: Client<Connection.ConnectionLike>) => Promise<T> | T): Promise<T> {
> 		return await this.scope(client =>
> ```

no
___
*[`packages/database/src/client/Connection.ts` line 123 at r4](https://reviewable.io/reviews/contember/engine/294#-N6lj8ci9XciFRbu6cr4:-N6mJTMZENHXsgbF36aI:btp18a4) ([raw file](https://github.com/contember/engine/blob/3319b5c6adcf6c529ed52c5d623fc3a6d78f6eda/packages/database/src/client/Connection.ts#L123)):*
> rename ConnectionWithScope to Scopable
done

> add Sub generic parameter to Transactional
no need, TransactionLike is always passed in transaction()

> also maybe Transactional should extend Scopable, as transactions require scope capability to be present
that is implementation dependency
___
*[`packages/database/src/client/Connection.ts` line 137 at r4](https://reviewable.io/reviews/contember/engine/294#-N6ll9uJE-HurgjT6-1f:-N6mJq9_AduaNeTjm-aR:bqrzs05) ([raw file](https://github.com/contember/engine/blob/3319b5c6adcf6c529ed52c5d623fc3a6d78f6eda/packages/database/src/client/Connection.ts#L137)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

This seem like semantic downgrade, it would be much better to instead add generic parameter to `ConnectionLike` extend `ConnectionLike<TransactionLike>`
</blockquote></details>

it would introduce weird circular generic
___
*[`packages/engine-system-api/src/resolvers/mutation/MigrateMutationResolver.ts` line 43 at r4](https://reviewable.io/reviews/contember/engine/294#-N6lfZ3s3BdMK9TQKA87:-N6mKN3g0a5tjAvlTH9x:b-xwtojv) ([raw file](https://github.com/contember/engine/blob/3319b5c6adcf6c529ed52c5d623fc3a6d78f6eda/packages/engine-system-api/src/resolvers/mutation/MigrateMutationResolver.ts#L43)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

does manually rollbacking transaction not fucked up the state? why is that even allowed? why not rely on built-in rollback on throw?
</blockquote></details>

I prefer manual rollback, if possible.

Maybe we can create a class like `RollbackResult<Result>`?

**Review by JanTvrdik — APPROVED** [review]
> Reviewed 5 of 6 files at r5, 26 of 26 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/294)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)

**Pull request merged**
