### PR TITLE
allow to enable debug mode for a single request

### PR DESCRIPTION
**Pull request by matej21**
This change is [Reviewable](https://reviewable.io/reviews/contember/engine/330)

### CODE REVIEW

**Review by VojtaStanek — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/330)* status: all files reviewed, 1 unresolved discussion (waiting on @matej21)

___
*[`packages/engine-http/src/content/ContentApiMiddlewareFactory.ts` line 90 at r1](https://reviewable.io/reviews/contember/engine/330#-NCU71J7AePXVz25etT8:-NCU71J7AePXVz25etT9:b-quucxi) ([raw file](https://github.com/contember/engine/blob/c0815b13bcb4beef1671960ea466a476722e6859/packages/engine-http/src/content/ContentApiMiddlewareFactory.ts#L90)):*
> ```XML
> 
> 			const debugHeaderValue = request.get(debugHeader).trim()
> 			const requestDebug = debugHeaderValue === '1' && fetchedMemberships.some(it => schema.acl.roles[it.role]?.debug)
> ```

Stuctured header (RFC8941)?

**Review by VojtaStanek — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/330)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/330)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)

___
*[`packages/engine-http/src/content/ContentApiMiddlewareFactory.ts` line 90 at r1](https://reviewable.io/reviews/contember/engine/330#-NCU71J7AePXVz25etT8:-NCUHfA24B5B5kDMcQE7:b-dvq42z) ([raw file](https://github.com/contember/engine/blob/c0815b13bcb4beef1671960ea466a476722e6859/packages/engine-http/src/content/ContentApiMiddlewareFactory.ts#L90)):*
<details><summary><i>Previously, VojtaStanek (Vojta Staněk) wrote…</i></summary><blockquote>

Stuctured header (RFC8941)?
</blockquote></details>

it is actually not a boolean, it is a debug level. currently, we only support one level (1)

**Review by VojtaStanek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/330)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)

**Pull request merged**
