### PR TITLE
where predicate elimination

### PR DESCRIPTION
**Pull request by matej21**
This change is [Reviewable](https://reviewable.io/reviews/contember/engine/317)

### CODE REVIEW

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/317)* status: all files reviewed, 1 unresolved discussion (waiting on @matej21)

___
*[`packages/engine-content-api/src/acl/PredicatesInjector.ts` line 54 at r2](https://reviewable.io/reviews/contember/engine/317#-NBM5T-aEFC5iwWnPdBF:-NBM5T-aEFC5iwWnPdBG:undefined) ([raw file](https://github.com/contember/engine/blob/4a97cc9863acac9c82bce95272ae28068da51ccd/packages/engine-content-api/src/acl/PredicatesInjector.ts#L54)):*
> ```XML
> 		}
> 		for (let field of fields) {
> 			const [targetEntity, targetRelation] = acceptFieldVisitor(this.schema, entity, field, {
> ```





_Suggestion:_
```XML
			const [targetEntity, targetRelation] = acceptFieldVisitor(this.schema, entity, field, {
				visitColumn: () => [undefined, undefined],
				visitRelation: (_a, _b, targetEntity, targetRelation) => [targetEntity, targetRelation ?? undefined],
			})
```

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/317)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @JanTvrdik)

___
*[`packages/engine-content-api/src/acl/PredicatesInjector.ts` line 54 at r2](https://reviewable.io/reviews/contember/engine/317#-NBM5T-aEFC5iwWnPdBF:-NBMr9BQ-T7AFKFyOoN4:b-183qeh) ([raw file](https://github.com/contember/engine/blob/4a97cc9863acac9c82bce95272ae28068da51ccd/packages/engine-content-api/src/acl/PredicatesInjector.ts#L54)):*
> ```XML
> 		}
> 		for (let field of fields) {
> 			const [targetEntity, targetRelation] = acceptFieldVisitor(this.schema, entity, field, {
> ```

ts does not infer return type correctly

**Review by JanTvrdik — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/317)* status: all files reviewed, 3 unresolved discussions (waiting on @matej21)

___
*[`packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts` line 65 at r3](https://reviewable.io/reviews/contember/engine/317#-NBN6-Xv2GRl_zrtqigK:-NBN6-Xv2GRl_zrtqigL:b-izo458) ([raw file](https://github.com/contember/engine/blob/c4fd88330994eceafffb8b6cba941e8840034ccd/packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts#L65)):*
> ```XML
> 	}
> 
> 	private minimize(operands: Input.Where[], entity: Model.Entity, replacement: Input.Condition): Input.Where[] {
> ```

all optimizations are "minimiting". better name would be for example `crossOptimize`
___
*[`packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts` line 66 at r3](https://reviewable.io/reviews/contember/engine/317#-NBN4OiV86jbgxkJO0Un:-NBN4NKtE0IKCDkfIl0m:b-7s4sqq) ([raw file](https://github.com/contember/engine/blob/c4fd88330994eceafffb8b6cba941e8840034ccd/packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts#L66)):*
> ```XML
> 
> 	private minimize(operands: Input.Where[], entity: Model.Entity, replacement: Input.Condition): Input.Where[] {
> 		let result = [...operands]
> ```

const
___
*[`packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts` line 68 at r3](https://reviewable.io/reviews/contember/engine/317#-NBN4PmtEUqNh0udkPXu:-NBN4PmtEUqNh0udkPXv:b-7eq6y0) ([raw file](https://github.com/contember/engine/blob/c4fd88330994eceafffb8b6cba941e8840034ccd/packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts#L68)):*
> ```XML
> 		let result = [...operands]
> 		const count = result.length
> 		for (let i = 0; i < count; i++) {
> ```

how about



_Suggestion:_
```XML
		for (let i = 0; i < count; i++) {
			for (let j = 0; j < count; j++) {
				if (i !== j) {
					result[i] = replaceWhere(result[i], result[j], { [entity.primary]: replacement })
				}
			}
		}
```

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/engine/317)* status: all files reviewed, 3 unresolved discussions (waiting on @JanTvrdik)

___
*[`packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts` line 65 at r3](https://reviewable.io/reviews/contember/engine/317#-NBN6-Xv2GRl_zrtqigK:-NBNHrsH-siXveDVGDgY:b-896fix) ([raw file](https://github.com/contember/engine/blob/c4fd88330994eceafffb8b6cba941e8840034ccd/packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts#L65)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

all optimizations are "minimiting". better name would be for example `crossOptimize`
</blockquote></details>

Done.
___
*[`packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts` line 66 at r3](https://reviewable.io/reviews/contember/engine/317#-NBN4OiV86jbgxkJO0Un:-NBNHrjX1k3mPrLDFwZK:b-896fix) ([raw file](https://github.com/contember/engine/blob/c4fd88330994eceafffb8b6cba941e8840034ccd/packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts#L66)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

const
</blockquote></details>

Done.
___
*[`packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts` line 68 at r3](https://reviewable.io/reviews/contember/engine/317#-NBN4PmtEUqNh0udkPXu:-NBNHrLeATzC5zaw9d0G:b-896fix) ([raw file](https://github.com/contember/engine/blob/c4fd88330994eceafffb8b6cba941e8840034ccd/packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts#L68)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

how about
</blockquote></details>

Done.

**Review by JanTvrdik — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/317)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)

**Pull request merged**
